version : "3"
services:
  node-app:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        NODE_ENV: development
    volumes:
      - ./backend:/app
      - ./backend/node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USERNAME=ahmed
      - MONGO_PASSWORD=1234
      - MONGO_PORT=27017
    command: npm run dev

  react-app:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
      args:
        NODE_ENV: development
    container_name: react-app
    ports:
      - "3000:3000"
    command: npm start
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    volumes:
      - ./client/src:/client/src
      - react-nodes:/client/node_modules
    depends_on:
      - node-app


  mongo:
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=ahmed
      - MONGO_INITDB_ROOT_PASSWORD=1234
volumes:
  node_modules:
  react-nodes: