version : "3"
services:
  node-app:
    container_name: node-app
    restart: always
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
    depends_on:
      - mongo
      
  mongo:
    image: mongo
    container_name: mongoDB
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME="ahmed"
      - MONGO_INITDB_ROOT_PASSWORD="1234"
    volumes:
      - mongo-db:/data/db

volumes:
  mongo-db:
    